'use strict';
// Configuracao PUBLICA. Nunca usar service_role, sb_secret_ ou senha aqui.
const PUBLIC={url:'https://dhddjynkjwsrxcfepwkc.supabase.co',key:'sb_publishable_5qzbaCZsu8DFIhe4oUkTtg_pLgMYFCl'};
const P='super-bi-online-v1';
const $=selector=>document.querySelector(selector);
const safe=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(Number(value||0));
const date=value=>new Date(value).toLocaleString('pt-BR');
let api=null,room=localStorage.getItem(P+'room'),state=null,tab='acoes',busy=false,modalHandler=null,retry=null,pollTimer=null,pollBusy=false;
let soundOn=localStorage.getItem(P+'sound')==='1',audio=null;
function notice(text,bad=false){const el=$('#notice');el.textContent=text;el.className='notice'+(bad?' error':'');setTimeout(()=>{if(el.textContent===text)el.classList.add('hidden')},7000)}
function soundButton(){$('#sound').textContent=soundOn?'🔔 Som ligado':'🔕 Ativar som';$('#sound').setAttribute('aria-pressed',String(soundOn))}
function chime(){if(!soundOn||document.hidden)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;audio ||= new C();if(audio.state==='suspended')audio.resume().catch(()=>{});const start=audio.currentTime;[784,1046].forEach((frequency,index)=>{const oscillator=audio.createOscillator(),gain=audio.createGain(),at=start+index*.13;oscillator.type='sine';oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.0001,at);gain.gain.exponentialRampToValueAtTime(.17,at+.015);gain.gain.exponentialRampToValueAtTime(.0001,at+.24);oscillator.connect(gain);gain.connect(audio.destination);oscillator.start(at);oscillator.stop(at+.25)})}catch(error){console.warn('Som indisponível:',error)}}
$('#sound').addEventListener('click',async()=>{soundOn=!soundOn;localStorage.setItem(P+'sound',soundOn?'1':'0');soundButton();if(soundOn){try{const C=window.AudioContext||window.webkitAudioContext;if(C){audio ||= new C();await audio.resume();chime();notice('Som ativado neste aparelho. Mantenha a página aberta para ouvir os recebimentos.')}else notice('Este navegador não oferece suporte ao som.',true)}catch(error){notice('O navegador bloqueou o som. Toque novamente para ativar.',true)}}else notice('Som desativado neste aparelho.')});
soundButton();
async function rpc(name,args){if(!api)throw Error('A conexão ainda não foi estabelecida.');const {data,error}=await api.rpc(name,args);if(error)throw Error(error.message);return data}
function lobby(){clearInterval(pollTimer);state=null;$('#refresh').classList.add('hidden');$('#app').innerHTML=`<h2>Criar ou entrar em uma sala</h2><p class="muted">Até 6 jogadores, R$ 15.000 para cada um. Os dados ficam na mesa. Vocês escolhem quem será o banqueiro.</p><form id="create"><label>Seu nome</label><input required name="name" maxlength="40" value="${safe(localStorage.getItem(P+'name')||'')}"><button class="green" style="margin-top:12px">Criar sala</button></form><hr><form id="join"><label>Seu nome</label><input required name="name" maxlength="40" value="${safe(localStorage.getItem(P+'name')||'')}"><label>Código da sala</label><input required name="code" maxlength="6" minlength="6" placeholder="6 caracteres"><button style="margin-top:12px">Entrar na sala</button></form><p class="muted"><small>Use sempre o mesmo navegador; limpar os dados do site pode apagar sua sessão anônima.</small></p>`}
async function watchCredits(){if(!room||!state)return;const player=state.meu_jogador_id,key=P+'seen-'+room+'-'+player;const credits=await rpc('bi_meus_creditos',{p_partida:room});if(!Array.isArray(credits))return;const current=credits.map(t=>t.id),stored=localStorage.getItem(key);if(stored!==null){let seen=[];try{seen=JSON.parse(stored)}catch{}const known=new Set(Array.isArray(seen)?seen:[]),fresh=credits.filter(t=>!known.has(t.id));if(fresh.length&&soundOn){chime();notice('💰 Você recebeu '+money(fresh.reduce((sum,t)=>sum+Number(t.valor||0),0))+'!')}localStorage.setItem(key,JSON.stringify([...new Set([...current,...known])].slice(0,180)))}else localStorage.setItem(key,JSON.stringify(current))}
async function refresh(){if(!room||!api)return false;try{state=await rpc('bi_painel',{p_partida:room});render();try{await watchCredits()}catch(error){console.warn('Notificações de crédito:',error)}return true}catch(error){if(!state){room=null;localStorage.removeItem(P+'room');lobby()}notice('Falha ao atualizar sala: '+error.message,true);return false}}
function startPoll(){clearInterval(pollTimer);pollTimer=setInterval(async()=>{if(pollBusy||busy||document.hidden||$('#dlg').open)return;pollBusy=true;try{await refresh()}finally{pollBusy=false}},3500)}
async function connect(){if(!window.supabase?.createClient){notice('Não foi possível carregar a biblioteca Supabase. Verifique a conexão.',true);$('#app').textContent='Não foi possível carregar o aplicativo. Atualize a página.';return}try{api=window.supabase.createClient(PUBLIC.url,PUBLIC.key,{auth:{persistSession:true,autoRefreshToken:true}});let {data,error}=await api.auth.getSession();if(error)throw error;if(!data.session){const login=await api.auth.signInAnonymously();if(login.error)throw login.error}if(room&&await refresh()){startPoll();return}lobby()}catch(error){notice('Falha de autenticação: '+error.message,true);$('#app').textContent='Não foi possível entrar. Atualize a página.'}}
async function run(operation,closeAfter=false){if(busy)return;busy=true;try{const result=await operation();if(result===false)return;if(closeAfter)closeModal();notice('Operação realizada.');await refresh();return result}catch(error){notice(error.message||String(error),true);return null}finally{busy=false}}
function users(exceptMe=false,filter=null){return (state?.jogadores||[]).filter(j=>(!exceptMe||j.id!==state.meu_jogador_id)&&(!filter||filter(j))).map(j=>`<option value="${safe(j.id)}">${safe(j.nome)}${j.banqueiro?' 🏦':''}</option>`).join('')}
function chooser(exceptMe=false,filter=null){return `<label>Jogador</label><select name="target" required>${users(exceptMe,filter)}</select>`}
const amount=()=>'<label>Valor em reais</label><input name="amount" type="number" min="1" max="1000000000" step="1" required>';
const reason=(label,required=true)=>`<label>${safe(label)}</label><textarea name="reason" maxlength="140" ${required?'required':''}></textarea>`;
function modal(title,fields,callback){modalHandler=callback;$('#dlg-title').textContent=title;$('#fields').innerHTML=fields;$('#dlg').showModal()}
function closeModal(){$('#dlg').close();modalHandler=null}
async function idempotent(functionName,params){const signature=JSON.stringify({functionName,...params,p_chave:null});if(retry?.signature!==signature)retry={signature,key:crypto.randomUUID()};params.p_chave=retry.key;const result=await rpc(functionName,params);retry=null;return result}
function nameOf(id){return state.jogadores.find(j=>j.id===id)?.nome||'jogador'}
function transaction(action){const forms={transferir:['Transferir',chooser(true)+amount()+reason('Motivo (opcional)',false)],cobrar:['Cobrar aluguel',chooser(true)+amount()+reason('Propriedade (opcional)',false)],pagar_banco:['Pagar ao banco',amount()+reason('Motivo do pagamento')],hipotecar_tudo:['Hipotecar tudo',amount()+reason('Bens hipotecados')],hipotecar_algumas:['Hipotecar algumas coisas',amount()+reason('Quais bens serão hipotecados?')],banco_paga:['Banco paga jogador',chooser()+amount()+reason('Bônus ou notícia positiva')],salario:['Salário de passagem (+ R$ 2.000)',chooser()+'<p class="pill">Somente o escolhido recebe R$ 2.000.</p>']};const [title,fields]=forms[action];modal(title,fields,async form=>{const target=form.get('target')||null,value=action==='salario'?2000:Number(form.get('amount')),text=String(form.get('reason')||'').trim()||null;if(!Number.isSafeInteger(value)||value<1||value>1000000000)throw Error('Informe um valor válido em reais inteiros.');const confirmation=action==='salario'?`Creditar R$ 2.000 para ${nameOf(target)}?`:action==='banco_paga'?`O banco pagará ${money(value)} a ${nameOf(target)}?`:action==='transferir'?`Transferir ${money(value)} de sua conta para ${nameOf(target)}?`:action==='cobrar'?`Solicitar ${money(value)} de aluguel a ${nameOf(target)}?`:action==='pagar_banco'?`Pagar ${money(value)} de sua conta ao banco?`:`Receber ${money(value)} do banco pela hipoteca?`;if(!confirm(confirmation))return false;return idempotent('bi_operar',{p_partida:room,p_acao:action,p_alvo:target,p_valor:value,p_motivo:text,p_chave:null})})}
function properties(){return `<p class="muted">Cadastro opcional. Não altera o saldo.</p><button class="green" data-action="propertyNew">+ Registrar imóvel</button>${(state.meus_imoveis||[]).map(p=>`<div class="line row"><div><strong>${safe(p.cidade)}${p.propriedade?' · '+safe(p.propriedade):''}</strong><br><small>${p.casas} casa(s) · ${p.hoteis} hotel(is)</small></div><div><button data-action="propertyEdit" data-id="${safe(p.id)}">Editar</button> <button data-action="propertyDelete" data-id="${safe(p.id)}">Excluir</button></div></div>`).join('')||'<p class="muted">Nenhum imóvel registrado.</p>'}`}
function history(){const transactions=(state.historico||[]).map(t=>`<div class="line"><div class="row"><strong>${money(t.valor)} · ${safe(t.status)}</strong><small>${date(t.criada_em)}</small></div>${safe(t.de)} → ${safe(t.para)}<br><small>${safe(t.descricao)}</small></div>`).join('')||'<p class="muted">Nenhuma transação.</p>';const events=(state.eventos||[]).map(e=>`<div class="line"><small>${date(e.criada_em)}</small><br>${safe(e.descricao)}</div>`).join('')||'<p class="muted">Nenhum registro de prisão.</p>';return `<h2>Últimas transações</h2>${transactions}<h2 style="margin-top:22px">Prisão</h2>${events}`}
function render(){if(!state)return;const s=state,playing=s.status==='jogando',me=s.jogadores.find(j=>j.id===s.meu_jogador_id),bank=s.jogadores.find(j=>j.id===s.banqueiro_id);if(!me){notice('Jogador não localizado.',true);return}$('#refresh').classList.remove('hidden');let setup='';if(!playing){setup=`<hr><p>Compartilhe o código da sala. ${s.jogadores.length} jogador(es) presente(s). A ordem é decidida manualmente na mesa.</p>${s.sou_anfitriao?`<section class="card"><h2>Escolher o banqueiro</h2><p class="muted">Conversem e decidam. Você pode trocar a escolha enquanto a partida não começar.</p><form id="chooseBank"><label>Quem ficará responsável pelo banco?</label><select name="bank" required><option value="">Selecione um jogador</option>${s.jogadores.map(j=>`<option value="${safe(j.id)}" ${j.id===s.banqueiro_id?'selected':''}>${safe(j.nome)}</option>`).join('')}</select><button class="green" style="margin-top:12px">Definir banqueiro</button></form><p><button class="green" data-action="start" ${!bank||s.jogadores.length<2?'disabled':''}>Iniciar partida</button></p></section>`:'<p class="pill">O anfitrião definirá o banqueiro antes de começar.</p>'}`}
$('#app').innerHTML=`<div class="row"><div><span class="pill">Sala ${safe(s.codigo)}</span><h2 style="margin-top:12px">${playing?'Partida em andamento':'Esperando jogadores'}</h2><small>${bank?'🏦 Banqueiro escolhido: '+safe(bank.nome):'Banqueiro ainda não escolhido'}</small></div><div><button data-action="copy">Copiar código</button> <button data-action="leave">Sair da tela</button></div></div><hr><h2>Saldos dos jogadores</h2><div class="grid">${s.jogadores.map(j=>`<div class="player"><strong>${safe(j.nome)} ${j.id===me.id?'· você':''}</strong>${j.banqueiro?' <span class="pill">🏦 Banqueiro</span>':''}<div class="balance">${money(j.saldo)}</div><small>${j.preso?'🔒 Preso · faltam '+j.jogadas_restantes+' jogada(s)':''}</small></div>`).join('')}</div>${!playing?setup:`<hr><h2>Minha conta: ${money(me.saldo)}</h2><div class="tabs"><button data-tab="acoes" ${tab==='acoes'?'class="green"':''}>Operações</button><button data-tab="imoveis" ${tab==='imoveis'?'class="green"':''}>Meus imóveis</button><button data-tab="historico" ${tab==='historico'?'class="green"':''}>Histórico</button></div>${tab==='acoes'?`<div class="actions"><button data-action="transferir">↗ Transferir para jogador</button><button data-action="cobrar">🧾 Cobrar aluguel</button><button data-action="pagar_banco">🏦 Pagar ao banco</button><button data-action="hipotecar_tudo">🏠 Hipotecar tudo</button><button data-action="hipotecar_algumas">🏘 Hipotecar algumas coisas</button>${me.preso?'<button class="green" data-action="bail">🔓 Pagar fiança R$ 500</button>':''}</div>`:tab==='imoveis'?properties():history()}${s.cobrancas?.length?`<hr><h2>🔔 Cobranças pendentes</h2>${s.cobrancas.map(t=>`<div class="line row"><div><strong>${money(t.valor)} de ${safe(t.de)}</strong><br><small>${safe(t.motivo)}</small></div><div><button data-action="reject" data-id="${safe(t.id)}">Recusar</button> <button class="green" data-action="accept" data-id="${safe(t.id)}">Pagar</button></div></div>`).join('')}`:''}${s.sou_banqueiro?`<hr><span class="pill">Exclusivo do banqueiro</span><h2 style="margin-top:12px">Painel do banco</h2><p class="muted">Sua conta pessoal é separada do banco.</p><div class="actions"><button class="green" data-action="salario">+ R$ 2.000 · passagem</button><button data-action="banco_paga">💵 Banco paga jogador</button><button data-action="jail">🔒 Prender jogador</button><button data-action="jailTick">⏳ Registrar jogada perdida</button></div>`:''}`}`}
function propertyDialog(existing=null){modal(existing?'Editar imóvel':'Cadastrar imóvel',`<label>Cidade</label><input required name="city" maxlength="100" value="${safe(existing?.cidade||'')}"><label>Propriedade (opcional)</label><input name="property" maxlength="100" value="${safe(existing?.propriedade||'')}"><label>Casas</label><input required name="houses" type="number" min="0" max="99" value="${Number(existing?.casas||0)}"><label>Hotéis</label><input required name="hotels" type="number" min="0" max="99" value="${Number(existing?.hoteis||0)}">`,async form=>{const city=String(form.get('city')).trim(),houses=Number(form.get('houses')),hotels=Number(form.get('hotels'));if(!city||!Number.isInteger(houses)||!Number.isInteger(hotels)||houses<0||houses>99||hotels<0||hotels>99)throw Error('Revise os dados do imóvel.');return rpc('bi_salvar_imovel',{p_partida:room,p_registro:existing?.id||null,p_cidade:city,p_propriedade:String(form.get('property')).trim(),p_casas:houses,p_hoteis:hotels})})}
async function click(actionName,button){if(!state||busy)return;const ref=button.dataset.id;if(['transferir','cobrar','pagar_banco','hipotecar_tudo','hipotecar_algumas','banco_paga','salario'].includes(actionName)){transaction(actionName);return}if(actionName==='copy'){try{await navigator.clipboard.writeText(state.codigo);notice('Código copiado!')}catch{prompt('Copie o código:',state.codigo)}return}if(actionName==='leave'){if(confirm('Sair desta tela? Você pode retornar com o código e o mesmo navegador.')){room=null;localStorage.removeItem(P+'room');lobby()}return}if(actionName==='start'){if(confirm('Todos entraram e concordam com o banqueiro escolhido?'))await run(()=>rpc('bi_iniciar_partida',{p_partida:room}));return}if(actionName==='accept'||actionName==='reject'){const yes=actionName==='accept';if(confirm(yes?'Confirmar pagamento do aluguel?':'Recusar essa cobrança?'))await run(()=>rpc('bi_responder_aluguel',{p_transacao:ref,p_aceitar:yes}));return}if(actionName==='bail'){if(confirm('Pagar R$ 500 ao banco e sair da prisão?'))await run(()=>idempotent('bi_pagar_fianca',{p_partida:room,p_chave:null}));return}if(actionName==='jail'||actionName==='jailTick'){const can=actionName==='jail'?j=>!j.preso:j=>j.preso;if(!state.jogadores.some(can)){notice('Não há jogadores para esta operação.',true);return}modal(actionName==='jail'?'Prender por três jogadas':'Marcar jogada perdida',chooser(false,can)+'<p class="muted">Confira o tabuleiro antes de confirmar.</p>',async form=>{const target=form.get('target');if(!confirm(actionName==='jail'?`Prender ${nameOf(target)}?`:`Descontar uma jogada de ${nameOf(target)}?`))return false;return rpc('bi_controlar_prisao',{p_partida:room,p_jogador:target,p_acao:actionName==='jail'?'prender':'perder_jogada'})});return}if(actionName==='propertyNew'){propertyDialog();return}if(actionName==='propertyEdit'){const record=state.meus_imoveis.find(p=>p.id===ref);if(record)propertyDialog(record);return}if(actionName==='propertyDelete'&&confirm('Excluir este registro?'))await run(()=>rpc('bi_excluir_imovel',{p_partida:room,p_registro:ref}))}
$('#app').addEventListener('click',event=>{const tabButton=event.target.closest('[data-tab]');if(tabButton){tab=tabButton.dataset.tab;render();return}const button=event.target.closest('[data-action]');if(button)click(button.dataset.action,button)});
$('#app').addEventListener('submit',async event=>{if(!['create','join','chooseBank'].includes(event.target.id))return;event.preventDefault();const form=new FormData(event.target);if(event.target.id==='chooseBank'){const bank=form.get('bank');if(!bank){notice('Selecione o banqueiro.',true);return}await run(()=>rpc('bi_escolher_banqueiro',{p_partida:room,p_jogador:bank}));return}const name=String(form.get('name')||'').trim();if(!name||name.length>40){notice('Nome inválido.',true);return}await run(async()=>{const created=event.target.id==='create'?await rpc('bi_criar_sala',{p_nome:name}):await rpc('bi_entrar_sala',{p_codigo:String(form.get('code')).trim().toUpperCase(),p_nome:name});localStorage.setItem(P+'name',name);room=created.partida_id;localStorage.setItem(P+'room',room);await refresh();startPoll()})});
$('#dlg-form').addEventListener('submit',async event=>{event.preventDefault();if(!modalHandler||busy)return;const callback=modalHandler,form=new FormData(event.target);await run(()=>callback(form),true)});
$('#cancel').addEventListener('click',closeModal);
$('#refresh').addEventListener('click',refresh);
connect();
